image: oprax/python:latest

stages:
  - test
  - build
  - deploy

pyz:
  stage: build
  artifacts:
    name: "$CI_COMMIT_REF_SLUG"
    paths:
      - dist/backup_utils.pyz
  before_script:
    - pipenv install --dev
    - mkdir dist
  script: make build

.test_template:
  before_script:
    - pipenv install --dev
  script: make test

python3.5:
  stage: test
  image: oprax/python:3.5
  extends: .test_template

python3.6:
  stage: test
  image: oprax/python:3.6
  extends: .test_template

python3.7:
  stage: test
  image: oprax/python:3.7
  extends: .test_template

pypi:
  stage: deploy
  only:
   - master
  before_script:
   - pipenv install --dev
  script: make upload
