image: oprax/python:latest

stages:
  - test
  - build

build:pyz:
  stage: build
  artifacts:
    name: "$CI_COMMIT_REF_SLUG"
    paths:
      - dist/backup-utils.pyz
  before_script:
    - mkdir dist
  script: make build

.test_template:
  before_script:
    - pipenv install --dev
    - pipenv lock --pre
    - pipenv install --dev
  script: make test

test:python3.5:
  stage: test
  image: oprax/python:3.5
  extends: .test_template

test:python3.6:
  stage: test
  image: oprax/python:3.6
  extends: .test_template

test:python3.7:
  stage: test
  image: oprax/python:3.7
  extends: .test_template
